### ISSUE TITLE
Release 2.3.9 is not announced

### ISSUE THREAD

**Issue by pzygielo** [javaserverfaces/javaserverfaces.github.io#4]
Release [2.3.9](https://github.com/javaserverfaces/mojarra/releases/tag/2.3.9) is not announced at https://javaserverfaces.github.io/ (in **Latest News** section).

Also
*Download* :arrow_forward: *Stable Versions of Mojarra* :arrow_forward: *Current Release* :arrow_forward: *2.3.x releases*
still refers to `2.3.8`.

**Comment by edbratt** [comment]
This project is archived and is not being updated. Please refer to [Eclipse Mojarra](https://github.com/eclipse-ee4j/mojarra) for details about current versions. Thank you.

**Comment by pzygielo** [comment]
> This project is archived and is not being updated.
> Please refer to Eclipse Mojarra for details about current versions.

That's not what I understand from: https://github.com/javaee/javaserverfaces-spec#about or https://github.com/javaserverfaces/mojarra/issues/4358#issuecomment-477647115, at least for 2.3 spec.

As I referenced - 2.3.9 version by Oracle - it was released and is [available in Central](http://repo1.maven.org/maven2/org/glassfish/javax.faces/2.3.9), while the https://javaserverfaces.github.io/ was not updated.
